version: TinyLlama/TinyLlama-1.1B-Chat-v1.0  # huggingface model path
conv_version: llama # chat template, other options are: phi, llama, gemmma, etc
model_max_length: 2048 # max model input length
name: tinyllama # model name
